# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0004_auto_20160521_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='gaitid',
        ),
        migrations.AddField(
            model_name='program',
            name='gait_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ID'),
        ),
    ]
