# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0005_auto_20160521_1235'),
        ('activitydb', '0005_auto_20160521_1231'),
    ]

    operations = [
    ]
