# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0006_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='gait_id',
            new_name='gaitid',
        ),
    ]
